Improve and document the developer deployment process.
argoproj-labs/applicationset pull request #37
Opened 2020-09-04 13:04 UTC by dgoodwin

Rather than require developers to change on disk files in the git index,
or create custom patching solutions, introduce a make target that allows
us to build, push, and deploy manifests in a single command.

Adds namespace to the ServiceAccount subject in the ClusterRoleBinding,
as far as I can tell this was invalid yaml.

2020-09-04 17:06 UTC, mgoodness requested changes

2020-09-04 17:50 UTC, dgoodwin commented
PR updated, thanks!

2020-09-09 14:51 UTC, mgoodness approved these changes
LGTM

2020-09-14 01:39 UTC, xianlubird approved these changes

2020-09-14 01:39 UTC, merged