Corrected wrong info about path and path.basename
argoproj-labs/applicationset pull request #412
Opened 2021-11-11 09:30 UTC by olvesh

Corrected wrong info in doc about _Git Generator: Files_  fixed #407   by copying documentation from https://github.com/argoproj-labs/applicationset/issues/258#issuecomment-856140869 as suggested in https://github.com/argoproj-labs/applicationset/issues/407#issuecomment-961571470

2021-11-11 09:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj-labs/applicationset?pullRequest=412) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj-labs/applicationset?pullRequest=412) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj-labs/applicationset?pullRequest=412) it.</sub>

2021-11-15 15:51 UTC, crenshaw-dev requested changes

2021-11-15 15:51 UTC, crenshaw-dev commented on docs/Generators-Git.md
> +- `{{ path.basename }}`: basename of path to the folder containing the configuration file (eg clusterA)
```suggestion
- `{{path}}`: path to the folder containing the configuration file (e.g. /clusters/clusterA, if the config file was /clusters/clusterA/config.json)
- `{{path.basename}}`: basename of path to the folder containing the configuration file (e.g. clusterA)
```

Nitpicks for consistency with other examples/docs. 😃

2021-11-16 17:13 UTC, jgwest approved these changes
LGTM, thanks @olvesh! I merged this with the other PR targeting this file, and tweaked the formatting.

2021-11-16 17:14 UTC, merged